-- self explanative
--vim.cmd([[
--fun! CleanExtraSpaces()
--    let save_cursor = getpos(".")
--    let old_query = getreg('/')
--    silent! %s/\s\+$//e
--    call setpos('.', save_cursor)
--    call setreg('/', old_query)
--endfun
--
--if has("autocmd")
--    autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
--endif
--]])
